### ISSUE TITLE
[Epic] Update dotnet-isolated item templates to reflect new SDK-type binding

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-templates#1374]
Epic to track all of the template updates for the SDK-Binding feature
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-functions-templates/issues/1375
- [ ] https://github.com/Azure/azure-functions-templates/issues/1376
- [ ] https://github.com/Azure/azure-functions-templates/issues/1377
- [ ] https://github.com/Azure/azure-functions-templates/issues/1378
- [ ] https://github.com/Azure/azure-functions-templates/issues/1379
- [ ] https://github.com/Azure/azure-functions-templates/issues/1380
- [ ] https://github.com/Azure/azure-functions-templates/issues/1381
```
