### ISSUE TITLE
Add templates for TypeScript

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-templates#804]
Add templates for supported TypeScript scenarios, once Functions core tools supports TS.

**Comment by mhoeger** [comment]
Steps include: 
 - [ ] Create function app template
 - [ ] Create function templates (parity with other languages)
 - [ ] Separate list of templates that get served to Portal vs. local environments
 - [ ] Add TS template for local environments
